### ISSUE TITLE
Issue with case sensitivity of asset names on AEWeb

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-node#1049] opened 2023-05-24 12:58 UTC
### Describe the problem you discovered

Currently, asset names are case sensitive, which creates inconvenience and discomfort for users.

For instance, if I have an HTML page with the following code:
``<img src="assets/images/logo.png" alt="logo" style="width: 100px">``

And my asset is named "Logo.png" with an uppercase "L," AEWebsite fails to display the image correctly.

### Epic

#1062

**Comment by wassimans** [comment] 2024-10-18 16:21
The issue is addressed in [PR #1580](https://github.com/archethic-foundation/archethic-node/pull/1580).

I’ve implemented a fix that addresses the case sensitivity issue for asset paths by normalizing the file paths to lowercase. The fix includes tests for various cases such as mixed cases and file extensions.
The solution is now available in [PR #1580](https://github.com/archethic-foundation/archethic-node/pull/1580) for review.

**Closed** 2024-10-22 16:00 UTC
Labels: bug, good first issue, API
