### ISSUE TITLE
Timeout for transaction's context notification

### ISSUE THREAD

**Issue by ghost** [archethic-foundation/archethic-node#273] opened 2022-04-05 21:29 UTC
### What happened?

During the transaction's validation workflow for oracle transactions, after some time, the cross-validation nodes notify the coordinator about the context, but the coordinator doesn't receive the notification, which causes a timeout because of no cross-validations nodes confirmations.

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/42943690/161852312-977dbe12-e361-4e00-834b-6785bb859623.png">

### What is expected?

During the validation, cross-validation nodes notify the coordinator to inform about their availability and also some P2P availability regarding chain and beacon storage nodes.
Once the success of the notification, the coordinator should receive this notification and continue in the workflow.

**Comment by internet-zero** [comment] 2022-04-08 07:18
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/273?planning-poker) with ZenHub @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris

**Comment by samuel-uniris** [comment] 2022-05-19 15:39
It might be related to this:

```
node3_1      | ** (exit) an exception was raised:
node3_1      |     ** (FunctionClauseError) no function clause matching in Archethic.Mining.DistributedWorkflow.handle_event/4
node3_1      |         (archethic 0.14.0) lib/archethic/mining/distributed_workflow.ex:182: Archethic.Mining.DistributedWorkflow.handle_event(:cast, {:add_mining_context, <<0, 1, 190, 20, 188, 141, 156, 135, 91, 37, 96, 187, 27, 24, 41, 130, 118, 93, 43, 240, 229, 97, 227, 194, 31, 97, 228, 78, 156, 194, 154, 74, 160, 104>>, [%Archethic.P2P.Node{authorization_date: ~U[2022-05-19 15:30:00Z], authorized?: true, availability_history: <<1::size(1)>>, available?: true, average_availability: 1.0, enrollment_date: ~U[2022-05-19 15:28:38.830Z], first_public_key: <<0, 1, 221, 229, 74, 49, 62, 93, 205, 115, 228, 19, 116, 140, 191, 102, 121, 240, 119, 23, 248, 189, 198, 108, 190, 143, 152, 30, 30, 71, 90, 152, 96, 92>>, geo_patch: "CFF", http_port: 40000, ip: {172, 16, 1, 12}, last_address: <<0, 0, 21, 54, 100, 105, 120, 247, 5, 46, 184, 90, 16, 15, 226, 63, 255, 210, 156, 75, 237, 164, 143, 152, 36, 193, 183, 99, 82, 119, 34, 6, 104, 210>>, last_public_key: <<0, 1, 221, 229, 74, 49, 62, 93, 205, 115, 228, 19, 116, 140, 191, 102, 121, 240, 119, 23, 248, 189, 198, 108, 190, 143, 152, 30, 30, 71, 90, 152, 96, 92>>, network_patch: "CFF", origin_public_key: <<0, 1, 9, 167, 31, 52, 28, 59, 133, 40, 222, 43, 25, 98, 111, 127, 181, 109, 221, 188, 44, 114, 121, 27, 240, 247, 124, 55, 70, 29, 231, 202, ...>>, port: 30002, reward_address: <<0, 0, 229, 241, 30, 90, 96, 214, 159, 56, 218, 172, 131, 194, 53, 19, 166, 79, 142, 24, 115, 188, 68, 202, 66, 176, 67, 223, 75, 130, ...>>, transport: :tcp}], <<3::size(3)>>, <<3::size(3)>>}, :wait_cross_validation_stamps, %{context: %Archethic.Mining.ValidationContext{beacon_storage_nodes: [%Archethic.P2P.Node{authorization_date: ~U[2022-05-19 15:28:23Z], authorized?: true, availability_history: <<1::size(1)>>, available?: true, average_availability: 1.0, enrollment_date: ~U[2022-05-19 15:28:23.394Z], first_public_key: <<0, 1, 29, 150, 125, 113, 178, 225, 53, 200, 66, 6, 221, 209, 8, 181, 146, 90, 44, 217, 156, 142, 188, 90, 181, 216, 253, 46, 201, 64, 12, 227, 201, 138>>, geo_patch: "AFF", http_port: 40000, ip: {172, 16, 1, 10}, last_address: <<0, 0, 238, 157, 220, 82, 41, 235, 255, 225, 151, 39, 112, 88, 241, 26, 65, 226, 34, 82, 216, 106, 144, 76, 140, 188, 243, 140, 30, 252, 66, 171, 80, 101>>, last_public_key: <<0, 1, 29, 150, 125, 113, 178, 225, 53, 200, 66, 6, 221, 209, 8, 181, 146, 90, 44, 217, 156, 142, 188, 90, 181, 216, 253, 46, 201, 64, 12, 227, 201, 138>>, network_patch: "AFF", origin_public_key: <<0, 1, 241, 82, 32, 209, 186, 92, 17, 249, 38, 128, 72, 56, 249, 214, 86, 118, 71, 166, 49, 126, 66, 66, 143, 6, 161, 214, 40, 217, 229, 68, 187, ...>>, port: 30002, reward_address: <<0, 0, 110, 165, 180, 212, 247, 242, 174, 222, 111, 150, 241, 41, 35, 114, 75, 26, 31, 147, 10, 28, 108, 161, 163, 91, 194, 155, 76, 79, 139, ...>>, transport: :tcp}, %Archethic.P2P.Node{authorization_date: ~U[2022-05-19 15:30:00Z], authorized?: true, availability_history: <<1::size(1)>>, available?: true, average_availability: 1.0, enrollment_date: ~U[2022-05-19 15:28:38.830Z], first_public_key: <<0, 1, 221, 229, 74, 49, 62, 93, 205, 115, 228, 19, 116, 140, 191, 102, 121, 240, 119, 23, 248, 189, 198, 108, 190, 143, 152, 30, 30, 71, 90, 152, 96, 92>>, geo_patch: "CFF", http_port: 40000, ip: {172, 16, 1, 12}, last_address: <<0, 0, 21, 54, 100, 105, 120, 247, 5, 46, 184, 90, 16, 15, 226, 63, 255, 210, 156, 75, 237, 164, 143, 152, 36, 193, 183, 99, 82, 119, 34, 6, 104, 210>>, last_public_key: <<0, 1, 221, 229, 74, 49, 62, 93, 205, 115, 228, 19, 116, 140, 191, 102, 121, 240, 119, 23, 248, 189, 198, 108, 190, 143, 152, 30, 30, 71, 90, 152, 96, 92>>, network_patch: "CFF", origin_public_key: <<0, 1, 9, 167, 31, 52, 28, 59, 133, 40, 222, 43, 25, 98, 111, 127, 181, 109, 221, 188, 44, 114, 121, 27, 240, 247, 124, 55, 70, 29, 231, 202, ...>>, port: 30002, reward_address: <<0, 0, 229, 241, 30, 90, 96, 214, 159, 56, 218, 172, 131, 194, 53, 19, 166, 79, 142, 24, 115, 188, 68, 202, 66, 176, 67, 223, 75, 130, ...>>, transport: :tcp}, %Archethic.P2P.Node{authorization_date: ~U[2022-05-19 15:30:00Z], authorized?: true, availability_history: <<1::size(1)>>, available?: true, average_availability: 1.0, enrollment_date: ~U[2022-05-19 15:28:32.031Z], first_public_key: <<0, 1, 190, 20, 188, 141, 156, 135, 91, 37, 96, 187, 27, 24, 41, 130, 118, 93, 43, 240, 229, 97, 227, 194, 31, 97, 228, 78, 156, 194, 154, 74, 160, 104>>, geo_patch: "3C7", http_port: 40000, ip: {172, 16, 1, 11}, last_address: <<0, 0, 141, 83, 46, 255, 162, 69, 241, 157, 120, 84, 165, 133, 135, 94, 245, 149, 16, 239, 130, 214, 62, 81, 49, 250, 118, 108, 244, 124, 188, 135, 215, 230>>, last_public_key: <<0, 1, 190, 20, 188, 141, 156, 135, 91, 37, 96, 187, 27, 24, 41, 130, 118, 93, 43, 240, 229, 97, 227, 194, 31, 97, 228, 78, 156, 194, 154, 74, 160, ...>>, network_patch: "3C7", origin_public_key: <<0, 1, 213, 247, 163, 112, 192, 38, 151, 142, 219, 232, 45, 247, 139, 98, 206, 113, 176, 28, 229, 153, 139, 127, 237, 26, 29, 13, 2, 164, 233, ...>>, port: 30002, reward_address: <<0, 0, 210, 215, 125, 252, 245, 205, 206, 163, 87, 19, 163, 20, 183, 2, 48, 171, 30, 145, 43, 19, 21, 144, 49, 168, 180, 86, 91, ...>>, transport: :tcp}], beacon_storage_nodes_view: <<7::size(3)>>, chain_storage_nodes: [%Archethic.P2P.Node{authorization_date: ~U[2022-05-19 15:30:00Z], authorized?: true, availability_history: <<1::size(1)>>, available?: true, average_availability: 1.0, enrollment_date: ~U[2022-05-19 15:28:38.830Z], first_public_key: <<0, 1, 221, 229, 74, 49, 62, 93, 205, 115, 228, 19, 116, 140, 191, 102, 121, 240, 119, 23, 248, 189, 198, 108, 190, 143, 152, 30, 30, 71, 90, 152, 96, 92>>, geo_patch: "CFF", http_port: 40000, ip: {172, 16, 1, 12}, last_address: <<0, 0, 21, 54, 100, 105, 120, 247, 5, 46, 184, 90, 16, 15, 226, 63, 255, 210, 156, 75, 237, 164, 143, 152, 36, 193, 183, 99, 82, 119, 34, 6, 104, 210>>, last_public_key: <<0, 1, 221, 229, 74, 49, 62, 93, 205, 115, 228, 19, 116, 140, 191, 102, 121, 240, 119, 23, 248, 189, 198, 108, 190, 143, 152, 30, 30, 71, 90, 152, 96, ...>>, network_patch: "CFF", origin_public_key: <<0, 1, 9, 167, 31, 52, 28, 59, 133, 40, 222, 43, 25, 98, 111, 127, 181, 109, 221, 188, 44, 114, 121, 27, 240, 247, 124, 55, 70, 29, 231, ...>>, port: 30002, reward_address: <<0, 0, 229, 241, 30, 90, 96, 214, 159, 56, 218, 172, 131, 194, 53, 19, 166, 79, 142, 24, 115, 188, 68, 202, 66, 176, 67, 223, 75, ...>>, transport: :tcp}, %Archethic.P2P.Node{authorization_date: ~U[2022-05-19 15:28:23Z], authorized?: true, availability_history: <<1::size(1)>>, available?: true, average_availability: 1.0, enrollment_date: ~U[2022-05-19 15:28:23.394Z], first_public_key: <<0, 1, 29, 150, 125, 113, 178, 225, 53, 200, 66, 6, 221, 209, 8, 181, 146, 90, 44, 217, 156, 142, 188, 90, 181, 216, 253, 46, 201, 64, 12, 227, 201, 138>>, geo_patch: "AFF", http_port: 40000, ip: {172, 16, 1, 10}, last_address: <<0, 0, 238, 157, 220, 82, 41, 235, 255, 225, 151, 39, 112, 88, 241, 26, 65, 226, 34, 82, 216, 106, 144, 76, 140, 188, 243, 140, 30, 252, 66, 171, 80, ...>>, last_public_key: <<0, 1, 29, 150, 125, 113, 178, 225, 53, 200, 66, 6, 221, 209, 8, 181, 146, 90, 44, 217, 156, 142, 188, 90, 181, 216, 253, 46, 201, 64, 12, 227, ...>>, network_patch: "AFF", origin_public_key: <<0, 1, 241, 82, 32, 209, 186, 92, 17, 249, 38, 128, 72, 56, 249, 214, 86, 118, 71, 166, 49, 126, 66, 66, 143, 6, 161, 214, 40, 217, ...>>, port: 30002, reward_address: <<0, 0, 110, 165, 180, 212, 247, 242, 174, 222, 111, 150, 241, 41, 35, 114, 75, 26, 31, 147, 10, 28, 108, 161, 163, 91, 194, 155, ...>>, transport: :tcp}, %Archethic.P2P.Node{authorization_date: ~U[2022-05-19 15:30:00Z], authorized?: true, availability_history: <<1::size(1)>>, available?: true, average_availability: 1.0, enrollment_date: ~U[2022-05-19 15:28:32.031Z], first_public_key: <<0, 1, 190, 20, 188, 141, 156, 135, 91, 37, 96, 187, 27, 24, 41, 130, 118, 93, 43, 240, 229, 97, 227, 19 (truncated
```

Add mining context have been received while the state is 
 in `wait_cross_validation_stamps`, causing crash

**Comment by samuel-uniris** [comment] 2022-05-23 20:08
The reason of this error is caused by an unexpected state change in the FSM.
So sometime, the status of the FSM goes from a `coordinator` to `cross_validator` and because it receives an event `add_mining_context` only handled by the `coordinator` state, it crashes the process.
Causing a non responsive communication with the other node as `cross_validator` and resulting into a timeout

**Comment by samuelmanzanera** [comment] 2023-01-05 15:56
Is it still relevant ?

**Comment by Neylix** [comment] 2023-01-05 16:17
Don't seen this issue in dev since a while. Happen on mainnet but it is expected behavior/
I think we can close this

**Closed** 2023-01-05 16:37 UTC
Labels: bug, mining, to-analyze
