### ISSUE TITLE
Resolve Metric issues, : poller don't get metrics correctly

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#455] opened 2022-07-17 18:35 UTC
### Describe the problem you discovered

- Metric should include all txns
- when timeout, metric dashboard should have metrics have of node itself.
![image](https://user-images.githubusercontent.com/26260538/179419884-5106b864-7870-43f5-8d56-f3caea075159.png)

Also on the dashboard it's seems that the datas are additionned instead of being averaged

### Describe the solution you'd like

Metric poller should retrieve datas without error.
Dashboard view should have accurate values

**Comment by apoorv-2204** [comment] 2022-07-25 08:18
Any steps to reproduce it ?

**Comment by internet-zero** [comment] 2022-07-29 08:37
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/455?planning-poker) with ZenHub @apoorv-2204 @Neylix @prix-uniris

**Comment by samuel-uniris** [comment] 2022-08-17 06:48
> Also on the dashboard it's seems that the datas are additionned instead of being averaged

I think this is coming become the metrics exposed are not within the interval of 5s but global. The distribution/histogram metrics expose insights but not aggregate by scrape interval.
Instead it's the aggregating tool which should do it.
The problem is the _sum and _count metrics are increasing over time which is causing the increase line in the graph.
We should either:
- implement  a kind of `rate` (as in prometheus: https://prometheus.io/docs/prometheus/latest/querying/functions/#rate) 
- implement a kind of `increase` increase` (https://prometheus.io/docs/prometheus/latest/querying/functions/#increase)

For example something like: `increase[5s]   =  count at 10s - count at 5s`

**Comment by internet-zero** [comment] 2022-09-09 08:29
The issue estimate has been increased to 21, due to the increase in work

**Comment by samuelmanzanera** [comment] 2022-09-29 16:39
Closed by #590

**Closed** 2022-09-29 16:39 UTC
Labels: bug, feature, UI
