### ISSUE TITLE
Consensus not reached during tx validation

### ISSUE THREAD

**Issue by ghost** [archethic-foundation/archethic-node#397] opened 2022-06-23 15:35 UTC
### Describe the problem you discovered

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/42943690/175338078-1139c6f8-371b-49f5-8598-2e2831ba6758.png">

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/42943690/175338132-9e5dddc8-130f-4af9-8694-51eb00f09f1f.png">

**Comment by samuel-uniris** [comment] 2022-07-01 07:45
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-node/397?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris

**Comment by Neylix** [comment] 2022-07-01 08:03
I think we can reproduce this error by running the benchmark with `mix dev.lbench`

**Comment by Neylix** [comment] 2022-07-05 17:01
This error is caused by a problem of latency between nodes when there is several transactions including the same transaction chain in the same time :

![Consensus error](https://user-images.githubusercontent.com/26260538/177378617-eccabe1f-786d-4f69-a19f-99d01b579a9c.png)

In my opinion this error is "normal" and cannot be resolved as it is the result of decentralized system and atomic commitment

**Comment by Neylix** [comment] 2022-07-05 19:47
For network transaction we can see in log that there is a timestamp inconsistencie causing the consensus not reached : 

![image](https://user-images.githubusercontent.com/26260538/177404074-485b40ef-1d9e-4334-aa84-90980499748d.png)

This insconsistencie should be fixed by https://github.com/archethic-foundation/archethic-node/commit/dd0d0bcf20c021fe98f70fdbc7b4f57a9a6e966d

**Closed** 2022-09-08 13:47 UTC
Labels: bug, mining, to-analyze
