### ISSUE TITLE
Timestamp inconsistency during transaction validation

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#396] opened 2022-06-23 15:32 UTC
### Describe the problem you discovered

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/42943690/175335397-7c69020d-2bee-4838-afc7-63f04db08593.png">

### Describe the solution you'd like

Timestamp should have an accepted delay of 10s, a slight difference of time should be accepted.

**Comment by samuel-uniris** [comment] 2022-07-01 07:44
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-node/396?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris

**Comment by Neylix** [comment] 2022-07-01 08:02
I think we can reproduce this error by running the benchmark with `mix dev.lbench`

**Comment by Neylix** [comment] 2022-07-04 11:11
Fixed in https://github.com/archethic-foundation/archethic-node/commit/dd0d0bcf20c021fe98f70fdbc7b4f57a9a6e966d
The error was due to latency, sometime a node can handle the start mining message and send the cross validation message to other node before the other node had handle the start mining message. And so we have a timestamp inconsistencie.
To solve it we add a difference of 3 sec which is the default timeout for the start mining message

**Closed by Neylix** 2022-07-04 11:11 UTC
Labels: bug, mining
